### ISSUE TITLE
How do I set the spectral information of the emitter in the YAML file?

### ISSUE THREAD

**Issue by 1languan** [diegoroyo/tal#7]
Hello, I have a question. How do I set the spectral information of the emitter in the YAML file? Among the examples you provided, there is one where mitsuba_variant is set as scalar_spectral, but the spectral information appears to be the default RGB. I'm wondering how to add spectral information when writing a YAML file in order to simulate a laser pulse with a specific pulse width.

**Comment by diegoroyo** [comment]
Hi! I added two commits to tal and mitransient that add the functionality that you were asking for. You can install both libraries from source (clone the repo and use the script located in scripts/local_install.sh). These are the relevant changes:

* tal: https://github.com/diegoroyo/tal/commit/26a24bde3620af19fa1c25f56d41fbf21ab969e0
* mitransient: https://github.com/diegoroyo/mitransient/commit/6e96de24f3cc5cc3f34bef991f7e73bb2a6695ce

Let me know if they work for your case, I was able to run a small test sample.

Also, you might need to tweak additional stuff based on your needs. Let me know if I can assist with these:
* mitransient depends on mitsuba. In order to run spectral mode you need to compile mitsuba youself, especially llvm_spectral or cuda_spectral modes. The mitsuba python package only supports RGB mode.
* **At the end of the process, tal converts everything to single-wavelength.** If you want to extract each spectral channel separately you would need to modify tal or access mitransient/mitsuba's data directly. This change should be relatively easy. If you want help with this please tell me how you want to store your results so I know how to help you.

Hope that works for you

**Comment by 1languan** [comment]
Hello, I have a question. After installing the new version, when I give the command 'tal render nlos-z.yaml' , an error occurs in the program.Can you help me solve this problem?
tal render confocal-scene.yaml
Traceback (most recent call last):
  File "/home/cx/.local/bin/tal", line 8, in <module>
    sys.exit(main())
  File "/home/cx/.local/lib/python3.8/site-packages/tal/__main__.py", line 171, in main
    render_nlos_scene(config_file, args)
  File "/home/cx/.local/lib/python3.8/site-packages/tal/render/__init__.py", line 30, in render_nlos_scene
    return render.render_nlos_scene(config_path, args)
  File "/home/cx/.local/lib/python3.8/site-packages/tal/render/render.py", line 509, in render_nlos_scene
    return _main_render(config_path, args,
  File "/home/cx/.local/lib/python3.8/site-packages/tal/render/render.py", line 390, in _main_render
    __write_scene_xmls(args, mitsuba_backend, scene_config, root_dir)
  File "/home/cx/.local/lib/python3.8/site-packages/tal/render/render.py", line 112, in __write_scene_xmls
    steady_xml, ground_truth_xml, nlos_xml = mitsuba_backend.get_scene_xml(
  File "/home/cx/.local/lib/python3.8/site-packages/tal/render/mitsuba3_transient_nlos.py", line 498, in get_scene_xml
    mitsuba_version=get_scene_version(),
  File "/home/cx/.local/lib/python3.8/site-packages/tal/render/mitsuba3_transient_nlos.py", line 48, in get_scene_version
    return mi.__version__
AttributeError: module 'mitsuba_alias' has no attribute '__version__'
